import {
    airspaceCoordinationArea, ambush, artilleryFiringPosition, artilleryTargetIntelligenceZone,
    barrageFire, block, boundaries, breach, bypass, callForFireZone, canalize, censorZone,
    circularTarget, clear, contain, coordinatedFireLine, corridor, counterattack, cover,
    criticalFriendlyZone, deadSpaceArea, delay, fireSupportArea,
    fireSupportCoordinationLine, fix, flot, freeFireArea, groupOfTargets, isolate, lineOfContact,
    mainAttack, multilineBarrageFire, munitionFlightPath, namedAreaOfInterest, noFireLine,
    noFireArea, occupy, phaseLine, rectangularTarget, restrictedOperationsZone, restrictiveFireArea,
    restrictiveFireLine, sensorZone, supportingAttack, targetBuildUpArea, targetValueArea,
    targetedAreaOfInterest, terminallyGuidedMunitionFootprint, test, weaponsFreeZone,
    zoneOfResponsibility
} from './geometryconverter/index';

export const geometryConverter = {
    ["AIR CORRIDOR"]: require("./geometryconverter/air-corridor.js"),
    ["AIRSPACE COORDINATION AREA"]: airspaceCoordinationArea,
    ["AMBUSH"]: ambush,
    ["ARTILLERY FIRING POSITION"]: artilleryFiringPosition,
    ["ARTILLERY MANOEUVRE AREA"]: require("./geometryconverter/artillery-manoeuvre-area.js"),
    ["ARTILLERY RESTRICTED AREA"]: require("./geometryconverter/artillery-restricted-area.js"),
    ["ARTILLERY TARGET INTELLIGENCE ZONE"]: artilleryTargetIntelligenceZone,
    ["BARRAGE FIRE"]: barrageFire,
    ["BLOCK"]: block,
    ["BOUNDARIES"]: boundaries,
    ["BREACH"]: breach,
    ["BYPASS"]: bypass,
    ["CALL FOR FIRE ZONE"]: callForFireZone,
    ["CANALIZE"]: canalize,
    ["CENSOR ZONE"]: censorZone,
    ["CIRCULAR TARGET"]: circularTarget,
    ["CLEAR"]: clear,
    ["CONTAIN"]: contain,
    ["COORDINATED FIRE LINE"]: coordinatedFireLine,
    ["CORRIDOR"]: corridor,
    ["COUNTERATTACK"]: counterattack,
    ["COVER"]: cover.js,
    ["CRITICAL FRIENDLY ZONE"]: criticalFriendlyZone,
    ["DEAD SPACE AREA"]: deadSpaceArea,
    ["DELAY"]: delay,
    ["FIRE SUPPORT AREA"]: fireSupportArea,
    ["FIRE SUPPORT COORDINATION LINE"]: fireSupportCoordinationLine,
    ["FIX"]: fix,
    ["FLOT"]: flot,
    ["FREE FIRE AREA"]: freeFireArea,
    ["GROUP OF TARGETS"]: groupOfTargets,
    ["GUARD"]: require("./geometryconverter/guard.js"),
    ["ISOLATE"]: isolate,
    ["LINE OF CONTACT"]: lineOfContact,
    ["LOW LEVEL TRANSIT ROUTE"]: require("./geometryconverter/low-level-transit-route.js"),
    ["MAIN ATTACK"]: mainAttack,
    ["MULTILINE BARRAGE FIRE"]: multilineBarrageFire,
    ["MUNITION FLIGHT PATH"]: munitionFlightPath,
    ["NAMED AREA OF INTEREST"]: namedAreaOfInterest,
    ["NO FIRE AREA"]: noFireArea,
    ["NO FIRE LINE"]: noFireLine,
    ["OCCUPY"]: occupy,
    ["PHASE LINE"]: phaseLine,
    ["POSITION AREA FOR ARTILLERY"]: require("./geometryconverter/position-area-for-artillery.js"),
    ["RECTANGULAR TARGET"]: rectangularTarget,
    ["RESTRICTED OPERATIONS ZONE"]: restrictedOperationsZone,
    ["RESTRICTIVE FIRE AREA"]: restrictiveFireArea,
    ["RESTRICTIVE FIRE LINE"]: restrictiveFireLine,
    ["SAFE LANE"]: require("./geometryconverter/safe-lane.js"),
    ["SEARCH AREA"]: require("./geometryconverter/search-area.js"),
    ["SENSOR ZONE"]: sensorZone,
    ["SUPPORTING ATTACK"]: supportingAttack,
    ["TARGET BUILD-UP AREA"]: targetBuildUpArea,
    ["TARGET VALUE AREA"]: targetValueArea,
    ["TARGETED AREA OF INTEREST"]: targetedAreaOfInterest,
    ["TERMINALLY GUIDED MUNITION FOOTPRINT"]: terminallyGuidedMunitionFootprint,
    ["TEST"]: test,
    ["WEAPONS FREE ZONE"]: weaponsFreeZone,
    ["ZONE OF RESPONSIBILITY"]: zoneOfResponsibility
};
    